trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build, FirstJob !
    - bash: echo $(PiplineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: python --version
    - bash: java --version
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2 #make a copy from default to artifact directory
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash : ls _R $(Build.ArtifactStagingDirectory)

#  - job: SecondtJob
#    steps:
#    - bash: echo Build, SecondtJob !
#- stage: DevDeploy
#  variables:
#    environment: DevDeploy
#  dependsOn: Build
#  jobs:
#  - job: DevJob
#    steps:
#    - bash: echo $(environment), DevJob !
#- stage: QADeploy
#  variables:
#    environment: QADeploy
#  dependsOn: Build
#  jobs:
#  - job: QAtJob
#    steps:
#    - bash: echo $(environment), QAJob !
#- stage: ProdDeploy
#  dependsOn:
#  - DevDeploy   
#  - QADeploy
#  jobs:
#  - job: ProdJob
#    steps:
#    - bash: echo ProdDeploy, FirstJob ! 