trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build, FirstJob !
    - bash : echo $(PiplineLevelVariable)
  - job: SecondtJob
    steps:
    - bash: echo Build, SecondtJob !
- stage: DevDeploy
  variables:
    environment: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevJob
    steps:
    - bash: echo $(environment), DevJob !
- stage: QADeploy
  variables:
    environment: QADeploy
  dependsOn: Build
  jobs:
  - job: QAtJob
    steps:
    - bash: echo $(environment), QAJob !
- stage: ProdDeploy
  dependsOn:
  - DevDeploy   
  - QADeploy
  jobs:
  - job: ProdJob
    steps:
    - bash: echo ProdDeploy, FirstJob !


