trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Terraform, Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'Public_Key.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-ressource-manager-service-connection'
    backendAzureRmSubscriptionId: '4e8e9a40-72b1-4310-88a9-b2b0d84fb659'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'new-cloud-shell-storage-westeurope'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'csb1003200244281815Rania'
    backendAzureRmStorageAccountSku: 'storageaccountrania'
    backendAzureRmContainerName: 'ranialounasstoragecontainer'
    backendAzureRmKey: 'backend.tfstate'
    allowTelemetryCollection: false
    
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-ressource-manager-service-connection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    